export const FETCH_SAMPLE_REQUEST = 'FETCH_SAMPLE_SUCCESS';
export const FETCH_SAMPLE_SUCCESS = 'FETCH_SAMPLE_SUCCESS';
export const FETCH_SAMPLE_FAILURE = 'FETCH_SAMPLE_FAILURE';

// LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
// REGISTER
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
// FORGOT PASSWORD
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
// RESET PASSWORD
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
// RESEND VERIFICATION CODE
export const RESEND_CODE_REQUEST = 'RESEND_CODE_REQUEST';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const RESEND_CODE_FAILURE = 'RESEND_CODE_FAILURE';
// VERIFY
export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_VERIFY_FAILURE = 'USER_VERIFY_FAILURE';
// VIEW PROFILE DETAILS
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';
// UPDATE PROFILE DETAILS
export const USER_DETAILS_EDIT_REQUEST = 'USER_DETAILS_EDIT_REQUEST';
export const USER_DETAILS_EDIT_SUCCESS = 'USER_DETAILS_EDIT_SUCCESS';
export const USER_DETAILS_EDIT_FAILURE = 'USER_DETAILS_EDIT_FAILURE';
export const USER_DETAILS_UPDATE_REQUEST = 'USER_DETAILS_UPDATE_REQUEST';
export const USER_DETAILS_UPDATE_SUCCESS = 'USER_DETAILS_UPDATE_SUCCESS';
export const USER_DETAILS_UPDATE_FAILURE = 'USER_DETAILS_UPDATE_FAILURE';
// JOIN TOURNAMENT
export const JOIN_TOURNAMENT_REQUEST = 'JOIN_TOURNAMENT_REQUEST';
export const JOIN_TOURNAMENT_SUCCESS = 'JOIN_TOURNAMENT_SUCCESS';
export const JOIN_TOURNAMENT_FAILURE = 'JOIN_TOURNAMENT_FAILURE';
// GET ZIMPSL
export const ZIMPSL_REQUEST = 'ZIMPSL_REQUEST';
export const ZIMPSL_SUCCESS = 'ZIMPSL_SUCCESS';
export const ZIMPSL_FAILURE = 'ZIMPSL_FAILURE';
// GET ZIMPSL GAMEWEEKS
export const ZIMPSL_GAMEWEEKS_REQUEST = 'ZIMPSL_GAMEWEEKS_REQUEST';
export const ZIMPSL_GAMEWEEKS_SUCCESS = 'ZIMPSL_GAMEWEEKS_SUCCESS';
export const ZIMPSL_GAMEWEEKS_FAILURE = 'ZIMPSL_GAMEWEEKS_FAILURE';
// GET LEADERBOARD
export const ZIMPSL_LEADERBOARD_REQUEST = 'ZIMPSL_LEADERBOARD_REQUEST';
export const ZIMPSL_LEADERBOARD_SUCCESS = 'ZIMPSL_LEADERBOARD_SUCCESS';
export const ZIMPSL_LEADERBOARD_FAILURE = 'ZIMPSL_LEADERBOARD_FAILURE';
// GET TEAM LEADERBOARD
export const ZIMPSL_TEAM_LEADERBOARD_REQUEST = 'ZIMPSL_TEAM_LEADERBOARD_REQUEST';
export const ZIMPSL_TEAM_LEADERBOARD_SUCCESS = 'ZIMPSL_TEAM_LEADERBOARD_SUCCESS';
export const ZIMPSL_TEAM_LEADERBOARD_FAILURE = 'ZIMPSL_TEAM_LEADERBOARD_FAILURE';
// GET PLAYER POINTS
export const ZIMPSL_PLAYER_POINTS_REQUEST = 'ZIMPSL_PLAYER_POINTS_REQUEST';
export const ZIMPSL_PLAYER_POINTS_SUCCESS = 'ZIMPSL_PLAYER_POINTS_SUCCESS';
export const ZIMPSL_PLAYER_POINTS_FAILURE = 'ZIMPSL_PLAYER_POINTS_FAILURE';
// PREDICT FIXTURE
export const PREDICT_REQUEST = 'PREDICT_REQUEST';
export const PREDICT_SUCCESS = 'PREDICT_SUCCESS';
export const PREDICT_FAILURE = 'PREDICT_FAILURE';
// SEND MAIL
export const SEND_MAIL_REQUEST = "SEND_MAIL_REQUEST";
export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS";
export const SEND_MAIL_FAILURE = "SEND_MAIL_FAILURE";